version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:5.0.0
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
  kafka-siren:
    image: glyderj/kafka-siren:latest<localBuild>
    restart: always
    depends_on:
      - kafka
    ports:
      - "9095:9095"
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_EXPORTER_POLL_INTERVAL: 1 seconds
